version: '3'

services:

  chatto-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5000:5000"
    deploy:
      mode: replicated
      replicas: 1

  # mongo:
  #   image: 'mongo:4.2.17-bionic'
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_DATABASE: chattodb
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - ./db-data/mongo/:/data/db
